# @package _group_

dpr_wiki:
  _target_: dpr.data.retriever_data.CsvCtxSrc
  file: data.wikipedia_split.psgs_w100
  id_prefix: 'wiki:'

dpr_wiki_by_path:
  _target_: dpr.data.retriever_data.CustomCsvCtxSrc
  file_path: /mnt/data01/dpr_data/downloads/data/wikipedia_split/psgs_w100.tsv
  id_prefix: 'wiki:'

newspaper_archive:
  _target_: dpr.data.retriever_data.NewspaperArchiveCtxSrc
  path_pattern: /mnt/data01/pipeline_egress/all1933_size50_marchManifest/**/ocr_*
  layout_object: headline
  page_filter: 1

mnli_dev:
  _target_: dpr.data.retriever_data.MnliJsonlCtxSrc
  file: /mnt/data01/mnli_for_dpr_dev.jsonl
  passage_char_max: 500
  hypotheses: False

hf_datasets:
  _target_: dpr.data.retriever_data.HFDatasetsCtxSrc
  dataset: ag_news
  split: test
  passage_char_max: 500