# @package _group_

nq_train:
  _target_: dpr.data.biencoder_data.JsonQADataset
  file: data.retriever.nq-train

nq_train_hn1:
  _target_: dpr.data.biencoder_data.JsonQADataset
  file: data.retriever.nq-adv-hn-train

nq_dev:
  _target_: dpr.data.biencoder_data.JsonQADataset
  file: data.retriever.nq-dev

trivia_train:
  _target_: dpr.data.biencoder_data.JsonQADataset
  file: data.retriever.trivia-train

trivia_dev:
  _target_: dpr.data.biencoder_data.JsonQADataset
  file: data.retriever.trivia-dev

squad1_train:
  _target_: dpr.data.biencoder_data.JsonQADataset
  file: data.retriever.squad1-train

squad1_dev:
  _target_: dpr.data.biencoder_data.JsonQADataset
  file: data.retriever.squad1-dev

custom_train:
  _target_: dpr.data.biencoder_data.CustomJsonQADataset
  file_path: /home/silcock/topic/mnli/mnli_for_dpr.json
#  file_path: /srv/accnd/topic_edit_sent_pl/topic/dpr/train_data/mnli_for_dpr.json

custom_dev:
  _target_: dpr.data.biencoder_data.CustomJsonQADataset
  file_path: /home/silcock/topic/mnli/mnli_for_dpr_dev.json
#  file_path: /srv/accnd/topic_edit_sent_pl/topic/dpr/train_data/mnli_for_dpr_dev.json
